# .gitlab-ci.yml

image: python:3.7-stretch

before_script:
  - python --version
  - pip --version
  - pip install tox


stages:
  - test
  - lint
  - document
  - publish
#  - build


unittests_core:
  stage: test
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script:
    - tox -e unittests_core

unittests_ui:
  stage: test
  image: python:3.7-stretch
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  allow_failure: true  # because of problem with linux and pyside2
  script:
    - python --version
    - pip install tox
    - tox -e unittests_ui

systemtests_core:
  stage: test
  image: python:3.7-stretch
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  script:
    - python --version
    - pip install tox
    - tox -e systemtests_core

systemtests_ui:
  stage: test
  image: python:3.7-stretch
  coverage: '/^TOTAL.*\s+(\d+\%)$/'
  allow_failure: true  # because of problem with linux and pyside2
  script:
    - python --version
    - pip install tox
    - tox -e systemtests_ui

flake8:
  stage: lint
  image: python:3.7-stretch
  allow_failure: true
  script:
    - python --version
    - pip install tox
    - tox -e flake8

pylint:
  stage: lint
  image: python:3.7-stretch
  allow_failure: true
  script:
    - python --version
    - pip install tox
    - tox -e pylint

docs:
  stage: document
  image: python:3.7-stretch
  script:
    - tox -e apidocs
    - tox -e docs
  artifacts:
    paths:
      - docs/build/html/
    expire_in: 1 week

pages:
  stage: publish
  before_script:  # overwrite global settings for efficiency
    - echo "noop"
  dependencies:  # download artifacts of these jobs
    - docs
  script:
    - mv docs/build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - develop

# build exe
