
language: python

matrix:

  include:

    # ubuntu 16
    - name: "xenial-37-unittests_core"
      language: python
      python: 3.7
      dist: xenial
      env:
        - TOX_ENV=unittests_core

    - name: "xenial-37-unittests_ui"
      language: python
      python: 3.7
      dist: xenial
      env:
        - TOX_ENV=unittests_ui

    # macOS
    - name: "macOS-37-unittests_core"
      language: shell
      os: osx
      osx_image: xcode10.2
      env:
        - TOX_ENV=unittests_core

    - name: "macOS-37-unittests_ui"
      language: shell
      os: osx
      osx_image: xcode10.2
      env:
        - TOX_ENV=unittests_ui

    # windows 10
    - name: "windows-37-unittests_core"
      os: windows
      language: shell
      before_install: choco install python --version 3.7.3
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOX_ENV=unittests_core

    - name: "windows-37-unittests_ui"
      os: windows
      language: shell
      before_install: choco install python --version 3.7.3
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOX_ENV=unittests_ui

install:
  - pip3 install tox

script:
  - tox -e $TOX_ENV





#language : shell
#
#env:
#  - TOX_ENV=unittets_core
#  - TOX_ENV=unittests_ui
#  - TOX_ENV=systemtests_core
#  - TOX_ENV=systemtests_ui
#
#os:
#  - linux
#  - windows
#  - osx
#
#install:
#  # pip and conda will also need OpenSSL for Windows
#  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
#      choco install python;
#      export PATH="/c/Python37:/c/Python37/Scripts:$PATH";
#    fi;
##  - export PATH="$MINICONDA_PATH:$MINICONDA_SUB_PATH:$PATH";
#  - echo "Running on $TRAVIS_OS_NAME";
#  - pip3 install tox
#
#script:
#  - tox -e $TOX_ENV
##  - conda --version && python --version && pip --version;
## notifications:
##    email:
##        - [your email addres here without brackets and uncomment lines]
#
