
language: python

matrix:

  include:

    # ubuntu 16
    - name: "xenial-37-unittests_core"
      language: python
      python: 3.7
      dist: xenial
      env:
        - TOX_ENV=unittests_core

    # the combination of linux and pyside2 may currently fail
    - name: "xenial-37-unittests_ui"
      language: python
      python: 3.7
      dist: xenial
      env:
        - TOX_ENV=unittests_ui

    - name: "xenial-37-systemtests_core"
      language: python
      python: 3.7
      dist: xenial
      env:
        - TOX_ENV=systemtests_core

    # the combination of linux and pyside2 may currently fail
    - name: "xenial-37-systemtests_ui"
      language: python
      python: 3.7
      dist: xenial
      env:
        - TOX_ENV=systemtests_ui

    # macOS
    - name: "macOS-37-unittests_core"
      language: shell
      os: osx
      osx_image: xcode10.2
      env:
        - TOX_ENV=unittests_core

    - name: "macOS-37-unittests_ui"
      language: shell
      os: osx
      osx_image: xcode10.2
      env:
        - TOX_ENV=unittests_ui

    - name: "macOS-37-systemtests_core"
      language: shell
      os: osx
      osx_image: xcode10.2
      env:
        - TOX_ENV=systemtests_core

    - name: "macOS-37-systemtests_ui"
      language: shell
      os: osx
      osx_image: xcode10.2
      env:
        - TOX_ENV=systemtests_ui

    # windows 10
    - name: "windows-37-unittests_core"
      os: windows
      language: shell
      before_install: choco install python --version 3.7.3
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOX_ENV=unittests_core

    - name: "windows-37-unittests_ui"
      os: windows
      language: shell
      before_install: choco install python --version 3.7.3
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOX_ENV=unittests_ui

    - name: "windows-37-systemtests_core"
      os: windows
      language: shell
      before_install: choco install python --version 3.7.3
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOX_ENV=systemtests_core

    - name: "windows-37-systemtests_ui"
      os: windows
      language: shell
      before_install: choco install python --version 3.7.3
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - TOX_ENV=systemtests_ui

install:
  - pip3 install tox

script:
  - tox -e $TOX_ENV
