

name: $(Date:yyyyMMdd)$(Rev:.r)
trigger: none # will disable CI builds (but not PR builds)
# pull requests to every branch will trigger the CI


# TODO: Correct docs zipping
# TODO: Correct exe zipping
# TODO: Correctly package docs in exe
# TODO: Add test coverage reports (PublishTestResults@2|PublishCodeCoverageResults@1)
#  https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/python?view=azure-devops#publish-test-results


stages:

- stage: test
  displayName: Testing

  jobs:

  - job: 'test_ubuntu_16_04'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 3

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e unittests_core
      displayName: 'Run unittests_core'

    - script: tox -e unittests_ui
      displayName: 'Run unittests_ui'
      continueOnError: true  # temporarily fails gracefully on issue of linux with pyside2

    - script: tox -e systemtests_core
      displayName: 'Run systemtests_core'

    - script: tox -e systemtests_ui
      displayName: 'Run systemtests_ui'
      continueOnError: true  # temporarily fails gracefully on issue of linux with pyside2


  - job: 'test_macOS_10_13'
    pool:
      vmImage: 'macOS-10.13'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 3

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e unittests_core
      displayName: 'Run unittests_core'

    - script: tox -e unittests_ui
      displayName: 'Run unittests_ui'

    - script: tox -e systemtests_core
      displayName: 'Run systemtests_core'

    - script: tox -e systemtests_ui
      displayName: 'Run systemtests_ui'


  - job: 'test_vs2017_win2016'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 3

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e unittests_core
      displayName: 'Run unittests_core'

    - script: tox -e unittests_ui
      displayName: 'Run unittests_ui'

    - script: tox -e systemtests_core
      displayName: 'Run systemtests_core'

    - script: tox -e systemtests_ui
      displayName: 'Run systemtests_ui'


- stage: lint
  displayName: Linting
  dependsOn: [] # by specifying an empty array, this stage doesn't depend on the stage before it

  jobs:

  - job: 'flake8'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 3

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e flake8
      displayName: 'Run flake8'


  - job: 'pylint'
    pool:
      vmImage: 'ubuntu-16.04'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 3

    steps:
      - task: UsePythonVersion@0
        displayName: 'Use Python $(python.version)'
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: pip install tox
        displayName: 'Install tox'

      - script: tox -e pylint
        displayName: 'Run pylint'


- stage: docs
  displayName: Documentation
  dependsOn: [test, ]

  jobs:

  - job: 'docs'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 3

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e apidocs
      displayName: 'Run apidocs'

    - script: tox -e docs
      displayName: 'Run docs'

    # Archive Files
    # Compress files into .7z, .tar.gz, or .zip.
    - task: ArchiveFiles@2
      displayName: 'Archive docs'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/docs/build/html/'
        includeRootFolder: false
        archiveType: 'zip' # Options: zip, 7z, tar, wim
        tarCompression: none
        archiveFile: '$(Build.ArtifactStagingDirectory)/docs.zip'
        replaceExistingArchive: true
        verbose: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish docs'
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: docs


- stage: build
  displayName: Building
  dependsOn: [test, docs, ]

  jobs:

  - job: 'build_vs2017_win2016'
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 3

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - task: DownloadBuildArtifacts@0
      displayName: 'Download docs'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: docs
        itemPattern: '**'
        downloadPath: '$(System.ArtifactsDirectory)'

    # Extract Files
    # Extract a variety of archive and compression files such as .7z, .rar, .tar.gz, and .zip.
    - task: ExtractFiles@1
      displayName: 'Extract docs'
      inputs:
        archiveFilePatterns: '*.zip'
        destinationFolder: '$(Build.SourcesDirectory)/docs/build/html/'
        #cleanDestinationFolder: true

    - script: pip install tox
      displayName: 'Install tox'

    - script: tox -e exe
      displayName: 'Run exe'

    # Archive Files
    # Compress files into .7z, .tar.gz, or .zip.
    - task: ArchiveFiles@2
      displayName: 'Archive exe'
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)/dist/'
        includeRootFolder: false
        archiveType: 'zip' # Options: zip, 7z, tar, wim
        tarCompression: none
        archiveFile: '$(Build.ArtifactStagingDirectory)/exe.zip'
        replaceExistingArchive: true
        verbose: true

    - task: PublishBuildArtifacts@1
      displayName: 'Publish exe'
      inputs:
        pathtoPublish: $(Build.ArtifactStagingDirectory)
        artifactName: exe
